[pytest]
addopts = --disable-plugin-autoload -p pytest_asyncio.plugin
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:Changing state of started or joined application is deprecated:DeprecationWarning
