"""Explicit GPX formats for planned routes, simulated tracks, and Xcode."""
import math
from datetime import datetime, timedelta, timezone
from xml.etree import ElementTree as ET
from .routes import MAX_POINTS, Route, export_gpx, speed_value


def start_value(value):
    try:
        if not isinstance(value, str) or len(value) > 64:
            raise ValueError()
        start = datetime.fromisoformat(value.replace('Z', '+00:00'))
        if start.tzinfo is None or start.utcoffset() is None:
            raise ValueError()
        start = start.astimezone(timezone.utc)
        if not 1970 <= start.year <= 9998:
            raise ValueError()
        return start
    except (ValueError, TypeError, OverflowError):
        raise ValueError('Choose a valid start date and time with a time zone (1970 or later).') from None


def create_gpx(data):
    route = Route(data.get('points'), data.get('loop', False))
    format_ = data.get('format', 'legacy')
    if format_ == 'legacy':
        return export_gpx(route, data.get('speed', 10), data.get('name', 'RoutePilot route'))
    if format_ not in ('activity', 'route', 'xcode'):
        raise ValueError('Choose a timed track, planned route, or Xcode GPX format.')
    mode = data.get('mode', 'running')
    if mode not in ('stationary', 'running', 'driving'):
        raise ValueError('Choose stationary, running, or driving.')
    name = data.get('name', 'RoutePilot simulated run' if format_ == 'activity' else 'RoutePilot route')
    if not isinstance(name, str):
        raise ValueError('Enter a file name of 1–100 characters.')
    name = ' '.join(name.split())
    if not 1 <= len(name) <= 100 or any(ord(c) < 32 or 0xD800 <= ord(c) <= 0xDFFF or ord(c) in (0xFFFE, 0xFFFF) for c in name):
        raise ValueError('Enter a file name of 1–100 printable characters.')
    timed = format_ != 'route'
    if format_ == 'activity' and (mode == 'stationary' or route.total < .01):
        raise ValueError('A timed activity needs a moving route with two distinct points.')
    start = start_value(data.get('start_time')) if timed else None
    speed = speed_value(data.get('speed', 10)) if timed else None
    duration = route.total / (speed / 3.6) if timed else 0
    if duration > 365 * 86400:
        raise ValueError('This GPX would run longer than a year. Use a shorter route or higher speed.')
    if timed:
        try:
            start + timedelta(seconds=duration)
        except OverflowError:
            raise ValueError('The finish time is outside the supported date range.') from None
    root = ET.Element('gpx', version='1.1', creator='RoutePilot', xmlns='http://www.topografix.com/GPX/1/1')
    metadata = ET.SubElement(root, 'metadata')
    ET.SubElement(metadata, 'name').text = name
    description = 'Simulated track generated by RoutePilot; not a recorded workout.' if timed else 'Planned route created with RoutePilot; no recorded activity or timestamps.'
    ET.SubElement(metadata, 'desc').text = description
    if timed:
        ET.SubElement(metadata, 'time').text = start.isoformat().replace('+00:00', 'Z')
    if format_ == 'route':
        container = ET.SubElement(root, 'rte')
        ET.SubElement(container, 'name').text = name
        ET.SubElement(container, 'type').text = mode
        samples = [(None, p) for p in route.points]
        tag = 'rtept'
    else:
        # Reserve every corner, then fill long legs at ~1 s (coarser for large
        # exports). Integer microsecond keys prevent equal rounded timestamps.
        samples_by_time = {}
        budget = min(20_000, MAX_POINTS - len(route.points))
        interval = max(1.0, duration / (budget + 1))
        for i in range(1, min(budget, math.floor(duration / interval)) + 1):
            seconds = i * interval
            if seconds < duration:
                samples_by_time[round(seconds * 1_000_000)] = route.at(seconds * speed / 3.6)
        for meters, position in zip(route.cumulative, route.points):
            samples_by_time[round(meters / (speed / 3.6) * 1_000_000)] = position
        samples = sorted(samples_by_time.items())
        if format_ == 'xcode':
            container, tag = root, 'wpt'
        else:
            track = ET.SubElement(root, 'trk')
            ET.SubElement(track, 'name').text = name
            ET.SubElement(track, 'desc').text = description
            ET.SubElement(track, 'type').text = mode
            container, tag = ET.SubElement(track, 'trkseg'), 'trkpt'
    for microseconds, p in samples:
        node = ET.SubElement(container, tag, lat=f'{p[0]:.8f}', lon=f'{p[1]:.8f}')
        if microseconds is not None:
            timestamp = start + timedelta(microseconds=microseconds)
            ET.SubElement(node, 'time').text = timestamp.isoformat(timespec='microseconds').replace('+00:00', 'Z')
    return ET.tostring(root, encoding='utf-8', xml_declaration=True)
